/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.jonathanblum.wthwatchnow.manager.view;

import ch.jonathanblum.wthwatchnow.manager.model.Manga;
import java.text.SimpleDateFormat;

/**
 *
 * @author Jonathan Blum <jonathan.blum@eldhar.com
 */
public class MangaView extends javax.swing.JInternalFrame {
    private Manga currentManga;

    /**
     * Creates new form MangaView
     */
    public MangaView(Manga manga) {
        super("Manga", false, false, false, false);
        pack();
        setBorder(null);
        initComponents();
        changeManga(manga);
    }
    
    public final void changeManga(Manga next) {
        currentManga = next;
        setTitle(currentManga.getTitle());
        initData();
    }
    
    protected void initData() {
        if(currentManga == null)
            return;
        setStatus();
        setSynopsis();
        setGenres();
        setProducers();
        setProgress();
        setDates();
    }
    
    protected void setStatus() {
        String str = "Status: "; 
        /*
        switch(currentManga.getStatus()) {
            case 0: str += "Terminé"; break;
            case 1: str += "En cours"; break;
            case 2: str += "Planifié"; break;
            case 3: str += "TBA"; break;
            default: str+= "inconnu";
        }*/
        lbStatus.setText(str + currentManga.getStatus());
    }

    protected void setSynopsis() {
        tpSynopsis.setContentType("text/html");
        tpSynopsis.setText(currentManga.getSynopsis());
        tpSynopsis.setCaretPosition(0);
    }
    
    protected void setGenres() {
        lbGenres.setText("Genres : " + String.join(", ", currentManga.getGenres()));
    }
    protected void setProducers() {
        lbProducers.setText("Producteurs : " + String.join(", ", currentManga.getProducers()));
    }  
    
    protected void setProgress() {
        pbar1.setMaximum(currentManga.getMaxChap());
        pbar2.setMaximum(currentManga.getMaxChap());
        pbar3.setMaximum(currentManga.getMaxChap());
        pbar1.setValue(currentManga.getAiredChap());
        if(currentManga.getDlChap() > 0) {
            pbar2.setValue(currentManga.getDlChap());
            pbar3.setValue(currentManga.getReadChap());
            pbar3.setVisible(true);
        } else {
            pbar2.setValue(currentManga.getReadChap());
            pbar3.setVisible(false); 
        }
    }
    
    protected void setDates() {
        String date;
        SimpleDateFormat sdf = new SimpleDateFormat("d MMM yyyy");
        if(currentManga.getAiringDate() != null)
            lbAiringDate.setText("Début : " + sdf.format(currentManga.getAiringDate()));
        else 
            lbAiringDate.setText("Début: inconnu");
        if(currentManga.getEndDate() != null)
           lbEndDate.setText("Fin : " + sdf.format(currentManga.getEndDate()));
        else
           lbEndDate.setText("Fin: inconnu");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpManga = new javax.swing.JTabbedPane();
        pMangaInfo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpSynopsis = new javax.swing.JTextPane();
        lbPreview = new javax.swing.JLabel();
        lbProgress = new javax.swing.JLabel();
        pbar1 = new javax.swing.JProgressBar();
        pbar2 = new javax.swing.JProgressBar();
        pbar3 = new javax.swing.JProgressBar();
        lbStatus = new javax.swing.JLabel();
        lbAiringDate = new javax.swing.JLabel();
        lbEndDate = new javax.swing.JLabel();
        lbProducers = new javax.swing.JLabel();
        lbGenres = new javax.swing.JLabel();
        pMangaChapters = new javax.swing.JPanel();

        tpSynopsis.setEditable(false);
        jScrollPane2.setViewportView(tpSynopsis);

        lbPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empty.png"))); // NOI18N
        lbPreview.setText("jLabel1");

        lbProgress.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lbProgress.setText("Progression");

        pbar1.setMaximum(24);
        pbar1.setToolTipText("Épisodes parus");
        pbar1.setValue(20);
        pbar1.setMinimumSize(new java.awt.Dimension(10, 20));
        pbar1.setPreferredSize(new java.awt.Dimension(150, 20));
        pbar1.setRequestFocusEnabled(false);

        pbar2.setForeground(new java.awt.Color(255, 153, 0));
        pbar2.setMaximum(24);
        pbar2.setToolTipText("Épisodes téléchargés");
        pbar2.setValue(13);

        pbar3.setForeground(new java.awt.Color(51, 204, 0));
        pbar3.setMaximum(24);
        pbar3.setToolTipText("Épisodes vus");
        pbar3.setValue(12);
        pbar3.setMinimumSize(new java.awt.Dimension(10, 20));
        pbar3.setPreferredSize(new java.awt.Dimension(150, 20));

        lbStatus.setText("Status : To Be Announced");

        lbAiringDate.setText("Début:");

        lbEndDate.setText("Fin:");

        lbProducers.setText("Producteurs : ");

        lbGenres.setText("Genres :");

        javax.swing.GroupLayout pMangaInfoLayout = new javax.swing.GroupLayout(pMangaInfo);
        pMangaInfo.setLayout(pMangaInfoLayout);
        pMangaInfoLayout.setHorizontalGroup(
            pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMangaInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMangaInfoLayout.createSequentialGroup()
                        .addGroup(pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbProducers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(lbAiringDate, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMangaInfoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pbar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pbar2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pbar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pMangaInfoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pMangaInfoLayout.createSequentialGroup()
                        .addGroup(pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbGenres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pMangaInfoLayout.setVerticalGroup(
            pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMangaInfoLayout.createSequentialGroup()
                .addGroup(pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMangaInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbPreview))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMangaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMangaInfoLayout.createSequentialGroup()
                        .addComponent(lbProgress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbar2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbar3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(pMangaInfoLayout.createSequentialGroup()
                        .addComponent(lbStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAiringDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEndDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbProducers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbGenres)))
                .addContainerGap())
        );

        tabpManga.addTab("Info", pMangaInfo);

        javax.swing.GroupLayout pMangaChaptersLayout = new javax.swing.GroupLayout(pMangaChapters);
        pMangaChapters.setLayout(pMangaChaptersLayout);
        pMangaChaptersLayout.setHorizontalGroup(
            pMangaChaptersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        pMangaChaptersLayout.setVerticalGroup(
            pMangaChaptersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        tabpManga.addTab("Chapitres", pMangaChapters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpManga)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpManga)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAiringDate;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbGenres;
    private javax.swing.JLabel lbPreview;
    private javax.swing.JLabel lbProducers;
    private javax.swing.JLabel lbProgress;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JPanel pMangaChapters;
    private javax.swing.JPanel pMangaInfo;
    private javax.swing.JProgressBar pbar1;
    private javax.swing.JProgressBar pbar2;
    private javax.swing.JProgressBar pbar3;
    private javax.swing.JTabbedPane tabpManga;
    private javax.swing.JTextPane tpSynopsis;
    // End of variables declaration//GEN-END:variables
}
